development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: helpdesk
  pool: 5
  username: root
  password: holamundo
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: helpdesk_tests
  pool: 5
  username: root
  password: holamundo
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: helpdesk_production
  pool: 5
  username: root
  password: holamundo
  socket: /var/run/mysqld/mysqld.sock
